-- Seed every editable piece of copy currently hardcoded on the site.
-- Uses upsert so running this twice won't clobber manual edits.

insert into public.site_content (key, value) values
  -- Global / commerce
  ('site.domain', 'autounified.com'),
  ('site.price_usd', '1000'),
  ('site.price_label', '$1,000'),
  ('site.sales_email', 'sales@autounified.com'),
  ('site.buy_url', 'mailto:sales@autounified.com?subject=Acquisition%20%E2%80%94%20autounified.com&body=Hi%2C%20I%27d%20like%20to%20acquire%20autounified.com%20for%20USD%201%2C000.%20My%20preferred%20registrar%20is%3A%20'),
  ('site.question_url', 'mailto:sales@autounified.com?subject=Question%20%E2%80%94%20autounified.com'),

  -- Metadata
  ('meta.title', 'autounified.com — Premium AI Domain / $1,000 USD'),
  ('meta.description', 'autounified.com — a one-word .com for the age of autonomous, unified AI. One lot. $1,000 USD.'),
  ('meta.og_title', 'autounified.com — Premium AI Domain'),
  ('meta.og_description', 'A one-word .com for the age of autonomous, unified AI. $1,000 USD.'),

  -- Nav
  ('nav.lot_label', 'LOT / 001'),
  ('nav.domain_label', 'autounified.com'),
  ('nav.available_label', 'Available'),
  ('nav.cta', 'Buy → $1,000'),
  ('nav.link_thesis', 'Thesis'),
  ('nav.link_manifesto', 'Manifesto'),
  ('nav.link_buyers', 'Buyers'),
  ('nav.link_specs', 'Specs'),
  ('nav.link_system', 'System'),

  -- Hero
  ('hero.meta_1_label', '001'),
  ('hero.meta_1_value', 'Premium .com'),
  ('hero.meta_2_label', 'TLD'),
  ('hero.meta_2_value', '.com · gTLD'),
  ('hero.meta_3_label', 'LEN'),
  ('hero.meta_3_value', '12 chars · 0 hyphens'),
  ('hero.meta_4_label', 'LOT'),
  ('hero.meta_4_value', 'Edition I of I'),
  ('hero.eyebrow', 'Premium domain — for sale'),
  ('hero.live_label', 'Live'),
  ('hero.headline_part_1', 'auto'),
  ('hero.headline_part_2', 'unified'),
  ('hero.headline_part_3', '.com'),
  ('hero.sub', 'A one-word .com for the era when every agent, model & workflow becomes one automated system.'),
  ('hero.cta_primary', 'Acquire for $1,000'),
  ('hero.cta_secondary', 'See the Thesis'),
  ('hero.price_label', 'Price · one-time'),
  ('hero.price_tag', '/LOT·001'),
  ('hero.price_note', 'No broker fee. Buyer covers escrow (~1.5%).'),
  ('hero.whois_status', 'Listed — ready to transfer'),

  -- Marquee
  ('marquee.items', 'AUTOMATE,UNIFY,ORCHESTRATE,FEDERATE,COMPOSE,AGENT-NATIVE,MULTI-MODEL,INTEROPERABLE,SELF-DIRECTING,SOVEREIGN'),

  -- Flow / Thesis intro
  ('flow.section_label', '§ 01 / The Thesis'),
  ('flow.section_hint', 'fragmented → unified'),
  ('flow.eyebrow', 'Automation, unified'),
  ('flow.headline', 'Six broken stacks — one name that owns the category.'),
  ('flow.body', 'Every AI team today is stitching agents, models and tools with duct tape. The next decade belongs to the platform that makes them feel like one system — automatic and unified. This URL says that out loud.'),
  ('flow.point_1', 'One URL. One spelling. One story.'),
  ('flow.point_2', 'No hyphens, numbers, or plurals.'),
  ('flow.point_3', 'Literal meaning = your product promise.'),

  -- Manifesto (thesis)
  ('thesis.section_label', '§ 02 / Manifesto'),
  ('thesis.section_hint', 'why this name, why now'),
  ('thesis.auto_eyebrow', '/prefix — auto'),
  ('thesis.auto_title', 'auto'),
  ('thesis.auto_body', 'Greek autós — self. In 2026 it no longer means cars. It means systems that act without waiting to be told. Agents. Decisions at the speed of inference.'),
  ('thesis.unified_eyebrow', '/suffix — unified'),
  ('thesis.unified_title', 'unified'),
  ('thesis.unified_body', 'The layer that makes every model, tool & agent feel like one thing. Orchestration. Interoperability. A single surface for the many.'),
  ('thesis.point_1_title', 'Every AI stack is a mess.'),
  ('thesis.point_1_body', 'Dozens of models. Thousands of tools. Pipelines that break on Tuesdays. The winning product of the decade will make it feel like one thing.'),
  ('thesis.point_2_title', 'Autonomy without unity is chaos.'),
  ('thesis.point_2_body', 'Agents that act on their own are only valuable when they speak the same language, share memory and answer to a single system of record.'),
  ('thesis.point_3_title', 'The URL is the flag.'),
  ('thesis.point_3_body', 'You can engineer category leadership, but you can only buy the name for it once. autounified.com is the flag — said out loud, it sells itself.'),

  -- Audience / Buyers
  ('audience.section_label', '§ 03 / Intended Buyer'),
  ('audience.section_hint', 'six plausible owners'),
  ('audience.headline', 'Built for the team that wants the category-defining URL before anyone else thinks to ask.'),
  ('audience.buyer_a_title', 'AI Orchestration Platform'),
  ('audience.buyer_a_body', 'A control plane for agents, tools and models across every vendor. The name is the pitch.'),
  ('audience.buyer_b_title', 'Agentic Infrastructure Startup'),
  ('audience.buyer_b_body', 'One brand, one URL — pre-seed deck to Series C announcement. Zero re-branding tax.'),
  ('audience.buyer_c_title', 'Multi-Model Gateway'),
  ('audience.buyer_c_body', 'Unify OpenAI, Anthropic, xAI, open-source behind one contract. Your users never switch.'),
  ('audience.buyer_d_title', 'Enterprise AI Consultancy'),
  ('audience.buyer_d_body', 'Position above the implementation crowd. A name clients quote in the boardroom.'),
  ('audience.buyer_e_title', 'Autonomous Robotics OS'),
  ('audience.buyer_e_body', 'Literal reading: auto + unified. A fleet operating as a single mind.'),
  ('audience.buyer_f_title', 'Portfolio / Holding'),
  ('audience.buyer_f_body', 'Park it. Own the category phrase before competitors define it. Resale upside obvious.'),

  -- Specs
  ('specs.section_label', '§ 04 / Specification'),
  ('specs.section_hint', 'record sheet'),
  ('specs.cert_label', 'Certificate / AU-001'),
  ('specs.edition_label', 'Ed. I of I'),
  ('specs.issued', '04.2026'),
  ('specs.lot', 'AU-001'),
  ('specs.status', 'AVAILABLE'),
  ('specs.row_1_label', 'Domain'),
  ('specs.row_1_value', 'autounified.com'),
  ('specs.row_2_label', 'Top-level domain'),
  ('specs.row_2_value', '.com'),
  ('specs.row_3_label', 'Characters'),
  ('specs.row_3_value', '12'),
  ('specs.row_4_label', 'Syllables'),
  ('specs.row_4_value', '5 — au·to·u·ni·fied'),
  ('specs.row_5_label', 'Hyphens'),
  ('specs.row_5_value', '0'),
  ('specs.row_6_label', 'Numerals'),
  ('specs.row_6_value', '0'),
  ('specs.row_7_label', 'Pronunciation'),
  ('specs.row_7_value', '/ˈɔːtoʊ juːnɪfaɪd/'),
  ('specs.row_8_label', 'Semantic field'),
  ('specs.row_8_value', 'AI · Agents · Orchestration'),
  ('specs.row_9_label', 'Trademark conflict'),
  ('specs.row_9_value', 'None on USPTO (verify at close)'),
  ('specs.row_10_label', 'Transfer'),
  ('specs.row_10_value', 'Escrow.com or registrar push'),
  ('specs.row_11_label', 'Included'),
  ('specs.row_11_value', 'Full registrant transfer + auth code'),

  -- Price
  ('price.section_label', '§ 05 / Acquisition'),
  ('price.section_hint', 'one buyer · one wire · done'),
  ('price.eyebrow', 'Buy it now'),
  ('price.headline', 'A one-time acquisition. No renewals. No royalties. No catch.'),
  ('price.body', 'Transfer via Escrow.com (1.5% fee, paid by buyer) or direct push at your registrar — GoDaddy, Namecheap, Cloudflare, Dynadot. Funds clear, auth code sent. Usually same-day.'),
  ('price.step_1', 'You reach out. We confirm availability within the hour.'),
  ('price.step_2', 'Escrow opened. You wire USD 1,000.'),
  ('price.step_3', 'We push the domain. You control it before end of day.'),
  ('price.card_header', 'autounified.com — all-in'),
  ('price.feature_1', 'Ownership — 100% transferred'),
  ('price.feature_2', 'Escrow.com — buyer & seller protected'),
  ('price.feature_3', 'Transfer — usually same-day'),
  ('price.feature_4', 'Support — free DNS migration help'),
  ('price.cta_primary', 'Buy autounified.com'),
  ('price.cta_secondary', 'Ask a question'),
  ('price.footer_note', 'Secure · Escrow · Same-day'),

  -- System
  ('system.eyebrow', 'Final · The System, live'),
  ('system.headline_1', 'Watch it'),
  ('system.headline_2', 'unify'),
  ('system.subline', 'A live view of the plane.'),
  ('system.body', 'One domain. One control plane. Every signal in — one coordinated output out. This is what the name literally does.'),
  ('system.stat_1', 'Events / sec'),
  ('system.stat_2', 'Agents online'),
  ('system.stat_3', 'Uptime · 30d'),
  ('system.stat_4', 'Processed · total'),

  -- Footer
  ('footer.manifesto', 'Good names are bought by the people who move first. If you''re still on this page, you''re not first — but you could be second.'),
  ('footer.contact_label', 'Contact'),
  ('footer.process_label', 'Process'),
  ('footer.process_1', 'Escrow.com'),
  ('footer.process_2', 'Wire · Wise · ACH'),
  ('footer.process_3', 'Same-day transfer'),
  ('footer.sections_label', 'Sections'),
  ('footer.copyright', '© 2026 — Private listing. Not affiliated with any trademark holder.'),
  ('footer.lot', 'Lot 001 / Ed. I of I')
on conflict (key) do nothing;
